### ISSUE TITLE
Database location?

### ISSUE THREAD

**Issue by khromov** [ipfire/libloc#2]
👋 I am wondering where I can find the underlying databases that map between IP and country?

If the databases are not available for download, is it possible to create a short README that explains how to compile the project and generate them from scratch on a Linux machine?

**Comment by mtremer** [comment]
Hello Stanislav,

(I would recommend asking your questions on our mailing list: https://lists.ipfire.org/mailman/listinfo/location)

The compiled database is available for download over here: https://location.ipfire.org/databases/1/

The raw database is being downloaded from various sources using the location-importer script that is part of the source: https://git.ipfire.org/?p=location/libloc.git;a=blob;f=src/python/location-importer.in;h=ff90d915b33cd3b76c55549a8866e0a93cc82762;hb=HEAD

We currently lack some documentation, but most of the steps are pretty self-explanatory. Just run location-importer --help.

If you have any more questions, please email the list.

-Michael
